### ISSUE TITLE
Incorrect `chat_template` in `tokenizer_config.json`

### ISSUE THREAD

**Issue by taxmeifyoucan** [huggingface/optimum-intel#879]
**Optimum creates a wrong chat_template config when running on linux.** Using optimum-cli to conver llama 3.1 8b to int4 compression, the model fails to run using [samples from genai repo](https://github.com/openvinotoolkit/openvino.genai/tree/master/samples/python/chat_sample).

Running on Ubuntu 22.04 with Python 3.10.12, after successfully converting the model, the api returns an error: 
```
line 33, in main
   pipe.generate(prompt, config, streamer)
RuntimeError: Exception from ../../../../src/cpp/src/tokenizer.cpp:428:
Chat template for the current model is not supported by Jinja2Cpp. Please apply template manually to your prompt before calling generate. For exmaple: <start_of_turn>user{user_prompt}<end_of_turn><start_of_turn>model
```

Turns out the chat template in config json is wrong, it's long field which doesn't work with the model:
<details> 
<summary> Template is too long, click to expand</summary>
```
 "chat_template": "{{- bos_token }}\n{%- if custom_tools is defined %}\n    {%- set tools = custom_tools %}\n{%- endif %}\n{%- if not tools_in_user_message is defined %}\n    {%- set tools_in_user_message = true %}\n{%- endif %}\n{%- if not date_string is defined %}\n    {%- set date_string = \"26 Jul 2024\" %}\n{%- endif %}\n{%- if not tools is defined %}\n    {%- set tools = none %}\n{%- endif %}\n\n{#- This block extracts the system message, so we can slot it into the right place. #}\n{%- if messages[0]['role'] == 'system' %}\n    {%- set system_message = messages[0]['content']|trim %}\n    {%- set messages = messages[1:] %}\n{%- else %}\n    {%- set system_message = \"\" %}\n{%- endif %}\n\n{#- System message + builtin tools #}\n{{- \"<|start_header_id|>system<|end_header_id|>\\n\\n\" }}\n{%- if builtin_tools is defined or tools is not none %}\n    {{- \"Environment: ipython\\n\" }}\n{%- endif %}\n{%- if builtin_tools is defined %}\n    {{- \"Tools: \" + builtin_tools | reject('equalto', 'code_interpreter') | join(\", \") + \"\\n\\n\"}}\n{%- endif %}\n{{- \"Cutting Knowledge Date: December 2023\\n\" }}\n{{- \"Today Date: \" + date_string + \"\\n\\n\" }}\n{%- if tools is not none and not tools_in_user_message %}\n    {{- \"You have access to the following functions. To call a function, please respond with JSON for a function call.\" }}\n    {{- 'Respond in the format {\"name\": function name, \"parameters\": dictionary of argument name and its value}.' }}\n    {{- \"Do not use variables.\\n\\n\" }}\n    {%- for t in tools %}\n        {{- t | tojson(indent=4) }}\n        {{- \"\\n\\n\" }}\n    {%- endfor %}\n{%- endif %}\n{{- system_message }}\n{{- \"<|eot_id|>\" }}\n\n{#- Custom tools are passed in a user message with some extra guidance #}\n{%- if tools_in_user_message and not tools is none %}\n    {#- Extract the first user message so we can plug it in here #}\n    {%- if messages | length != 0 %}\n        {%- set first_user_message = messages[0]['content']|trim %}\n        {%- set messages = messages[1:] %}\n    {%- else %}\n        {{- raise_exception(\"Cannot put tools in the first user message when there's no first user message!\") }}\n{%- endif %}\n    {{- '<|start_header_id|>user<|end_header_id|>\\n\\n' -}}\n    {{- \"Given the following functions, please respond with a JSON for a function call \" }}\n    {{- \"with its proper arguments that best answers the given prompt.\\n\\n\" }}\n    {{- 'Respond in the format {\"name\": function name, \"parameters\": dictionary of argument name and its value}.' }}\n    {{- \"Do not use variables.\\n\\n\" }}\n    {%- for t in tools %}\n        {{- t | tojson(indent=4) }}\n        {{- \"\\n\\n\" }}\n    {%- endfor %}\n    {{- first_user_message + \"<|eot_id|>\"}}\n{%- endif %}\n\n{%- for message in messages %}\n    {%- if not (message.role == 'ipython' or message.role == 'tool' or 'tool_calls' in message) %}\n        {{- '<|start_header_id|>' + message['role'] + '<|end_header_id|>\\n\\n'+ message['content'] | trim + '<|eot_id|>' }}\n    {%- elif 'tool_calls' in message %}\n        {%- if not message.tool_calls|length == 1 %}\n            {{- raise_exception(\"This model only supports single tool-calls at once!\") }}\n        {%- endif %}\n        {%- set tool_call = message.tool_calls[0].function %}\n        {%- if builtin_tools is defined and tool_call.name in builtin_tools %}\n            {{- '<|start_header_id|>assistant<|end_header_id|>\\n\\n' -}}\n            {{- \"<|python_tag|>\" + tool_call.name + \".call(\" }}\n            {%- for arg_name, arg_val in tool_call.arguments | items %}\n                {{- arg_name + '=\"' + arg_val + '\"' }}\n                {%- if not loop.last %}\n                    {{- \", \" }}\n                {%- endif %}\n                {%- endfor %}\n            {{- \")\" }}\n        {%- else  %}\n            {{- '<|start_header_id|>assistant<|end_header_id|>\\n\\n' -}}\n            {{- '{\"name\": \"' + tool_call.name + '\", ' }}\n            {{- '\"parameters\": ' }}\n            {{- tool_call.arguments | tojson }}\n            {{- \"}\" }}\n        {%- endif %}\n        {%- if builtin_tools is defined %}\n            {#- This means we're in ipython mode #}\n            {{- \"<|eom_id|>\" }}\n        {%- else %}\n            {{- \"<|eot_id|>\" }}\n        {%- endif %}\n    {%- elif message.role == \"tool\" or message.role == \"ipython\" %}\n        {{- \"<|start_header_id|>ipython<|end_header_id|>\\n\\n\" }}\n        {%- if message.content is mapping or message.content is iterable %}\n            {{- message.content | tojson }}\n        {%- else %}\n            {{- message.content }}\n        {%- endif %}\n        {{- \"<|eot_id|>\" }}\n    {%- endif %}\n{%- endfor %}\n{%- if add_generation_prompt %}\n    {{- '<|start_header_id|>assistant<|end_header_id|>\\n\\n' }}\n{%- endif %}\n",
 ```
 </details>
 
 It's possible to fix it by changing the field in config to something more reasonable: 
 ```
   "chat_template": "{% set loop_messages = messages %}{% for message in loop_messages %}{% set content = '<|start_header_id|>' + message['role'] + '<|end_header_id|>\n\n'+ message['content'] | trim + '<|eot_id|>' %}{% if loop.index0 == 0 %}{% set content = bos_token + content %}{% endif %}{{ content }}{% endfor %}{{ '<|start_header_id|>assistant<|end_header_id|>\n\n' }}",
  ```

**Comment by CoZmoTheGod** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/6mkbh6xhau31g
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by enricozao** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/6mkbh6xhau31g
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by mohamed-elsankary** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/6mkbh6xhau31g
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by taxmeifyoucan** [comment]
omg f-ing scammer bots!

**Comment by eaidova** [comment]
@taxmeifyoucan please try to update openvino-genai on 2024.4 that was released yesterday, issue with llama3.1 8b chat template processing should be resolved

**Comment by taxmeifyoucan** [comment]
Using the optimizer and openvino on latest version, I am still getting the same issue. The default template is broken

```RuntimeError: Exception from ../../../../src/cpp/src/tokenizer.cpp:428:
Chat template for the current model is not supported by Jinja2Cpp. Please apply template manually to your prompt before calling generate. For exmaple: <start_of_turn>user{user_prompt}<end_of_turn><start_of_turn>model
```

**Comment by andrei-kochin** [comment]
@taxmeifyoucan seems like optimum-intel forces you to specific version of the OpenVINO.
Please make sure you try the latest optimum:
`python -m pip install git+https://github.com/huggingface/optimum-intel.git`

**Comment by eaidova** [comment]
not related to optimum-intel, issue on genai side was fixed sometime ago, can not reproduce with https://huggingface.co/llmware/llama-3.1-instruct-ov and openvno_genai 2024.6

so closing this

**Comment by Dazui-Wang** [comment]
I am experiencing the same issue when using OpenVINO 2025.1.0 and openvino-genai 2025.1.0 with the Qwen3-8B model. Could you please advise if there is any known solution or recommended workaround?

![Image](https://github.com/user-attachments/assets/34ad0534-851d-4f45-bbd7-e29d1f2842ad)

version:
(venv) [root@localhost model-test]# pip list|grep openvino
openvino                  2025.1.0             18503
openvino-genai            2025.1.0.0
openvino-telemetry        2025.1.0
openvino-tokenizers       2025.1.0.0
(venv) [root@localhost model-test]# pip list|grep optimum
optimum                   1.26.0.dev0
optimum-intel             1.23.0.dev0+37e8504
